/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.and.queue;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
      Stack<Integer>stack=new Stack<>();
      System.out.println(stack.peek());
      stack.push(5);
      stack.push(10);
      System.out.println(stack.toString());
      stack.push(20);
      stack.push(30);
      System.out.println(stack.toString());
      stack.pop();
      System.out.println(stack.toString());
      System.out.println(stack.peek());

      System.out.println("--------------------");

      Queue<Integer> queue = new Queue<>();
      System.out.println(queue.peek());
      queue.enqueue(2);
      queue.enqueue(4);
      System.out.println(queue.toString());
      queue.enqueue(8);
      queue.enqueue(10);
      System.out.println(queue.toString());
      queue.dequeue();
      System.out.println(queue.toString());
      System.out.println(queue.peek());
    }
}
