/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quickSort;

import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        App classUnderTest = new App();
      int[]arr={3,6,9,1};
     int[]arr2=App.QuickSort.sort(arr);
     assertArrayEquals(arr,arr2);

      int[]arr3={};
      int[]arr4=App.QuickSort.sort(arr3);
      assertArrayEquals(arr3,arr4);
    }
}
