/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quickSort;

import java.util.Arrays;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        int[]arr={3,6,9,1};
      System.out.println(Arrays.toString(QuickSort.sort(arr)));
    }



  public static class QuickSort {

    public static int[] sort(int[] arr){
      int left = 0;
      int right = arr.length -1;
      return quickSort(arr, left, right);

    }

    public static int[] quickSort(int[] arr, int left, int right){
      if(left < right ){
        int position = partition(arr, left,right);
        quickSort(arr, left, position -1 );
        quickSort(arr,position +1, right );

      }
      return arr;
    }

    private static int partition(int[] arr, int left, int right) {
      int pivot = arr[right];
      int low = left-1 ;
      int i;
      for( i = left; i< right; i++){
        if(arr[i] <= pivot){
          low++;
          swap(arr, low, i);
        }
      }
      swap(arr, low+1, right);
      return low+1;
    }

    private static void swap(int[] arr, int first, int second) {
      int temp = arr[first];
      arr[first]  = arr[second];
      arr[second] = temp;
    }
  }

}
