/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stackAndQueue;

import stackAndQueue.pseudoQueue.PseudoQueue;
import stackAndQueue.stackQueueBrackets.Brackets;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
      Stack<Integer>stack=new Stack<>();
      System.out.println(stack.peek());
      stack.push(5);
      stack.push(10);
      System.out.println(stack.toString());
      stack.push(20);
      stack.push(30);
      System.out.println(stack.toString());
      stack.pop();
      System.out.println(stack.toString());
      System.out.println(stack.peek());

      System.out.println("-------------------- Queue -------------------");

      Queue<Integer> queue = new Queue<>();
      System.out.println(queue.peek());
      queue.enqueue(2);
      queue.enqueue(4);
      System.out.println(queue.toString());
      queue.enqueue(8);
      queue.enqueue(10);
      System.out.println(queue.toString());
      queue.dequeue();
      System.out.println(queue.toString());
      System.out.println(queue.peek());

      System.out.println("-----------------Pseudo queue ---------------------");
      PseudoQueue<Integer> pseudoQueue=new PseudoQueue<>();
      pseudoQueue.enqueue(10);
      pseudoQueue.enqueue(20);
      System.out.println(pseudoQueue.toString());
      pseudoQueue.dequeue();
      System.out.println(pseudoQueue.toString());

      System.out.println("----------------------Brackets---------------------");
      Brackets<String> brackets=new Brackets<>();
      System.out.println(brackets.validateBrackets("(()"));
    }



}
