/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashTable;

import repeatedWord.Repeated;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        HashTable<Integer,Integer> hashTable=new HashTable<>();
        hashTable.add(1,5);
        hashTable.add(3,6);
        hashTable.add(51,10);
//      System.out.println( hashTable.get(1));
//      System.out.println( hashTable.contain(1));
//      System.out.println( hashTable.contain(6));


        String text ="It was a queer, sultry summer, the summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York...";
      Repeated repeated=new Repeated();
      System.out.println(repeated.repeatedWord(text));


    }


}
