/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package insertionSort;

import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void insertionSortTest() {
        App classUnderTest = new App();
        int[]arr={20,18,12,8,5,-2};
        int[]arr2={};
        assertEquals("[-2, 5, 8, 12, 18, 20]", Arrays.toString( classUnderTest.insertionSort(arr)));
      assertEquals("[]", Arrays.toString( classUnderTest.insertionSort(arr2)));


    }
}
